/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package most_active_cookie;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {

        if (args.length != 4 || !"-f".equals(args[0]) || !"-d".equals(args[2])) {
            System.out.println("Usage: ./[cmd] -f [FILENAME] -d [DATE]");
            System.exit(1);
        }

        String filename = args[1];
        
        String date = args[3];

        // System.out.println(new App().getGreeting());
    }
}
